### ISSUE TITLE
S3 uploaded files are private by default

### ISSUE THREAD

**Issue by dmarcos89** [Laravel-Backpack/FileManager#10]
Hi, i have been fighting with this error and couldnt find a solution yet, when trying to upload files to s3, it all works fine, only that files are set as private, not accesible via url. 

Looks like the fix was merged to master but not yet reflected in the package: https://github.com/barryvdh/elfinder-flysystem-driver/pull/72

If anyone has a workaround for this, greatly appreciated!
Thanks

**Comment by promatik** [comment]
Hi @dmarcos89!

It seems that @barryvdh haven't tagged a version on https://github.com/barryvdh/elfinder-flysystem-driver/ since [that commit](https://github.com/barryvdh/elfinder-flysystem-driver/pull/72).

**If this is possible for you**, I've used S3 with public files not on AWS but on DigitalOcean (it's also S3 API). Since all files were public, I set the space to public on DO, and it works because all files are public by default, it's a work around.

There are some untagged commits since the last version; https://github.com/barryvdh/elfinder-flysystem-driver/compare/v0.2.1...master and that's one of them, I think there are not much we can do on our side 😕

**Comment by barryvdh** [comment]
Tagged https://github.com/barryvdh/elfinder-flysystem-driver/releases/tag/v0.3.0

**Comment by barryvdh** [comment]
And https://github.com/barryvdh/laravel-elfinder/releases/tag/v0.4.7

**Comment by dmarcos89** [comment]
Thanks @promatik for the response, and @barryvdh for tagging the new versions! 👏

**Comment by promatik** [comment]
Perfect 👌
Thank you @barryvdh, this will be helpful for many.

@dmarcos89 with a `composer update` you get the new updates 🙌
