### ISSUE TITLE
How to retrieve thumbnail path in the view?

### ISSUE THREAD

**Issue by kee0624** [Laravel-Backpack/FileManager#17]
Hi, I am using lazyload for loading the big image in the front end, and I saw the elfinder is auto-generating the thumbnail on the backend, may I know how do I retrieve the thumbnail path and show it to the front end?

**Comment by promatik** [comment]
Hi @kee0624!
ElFinder generates thumbnails on demand, you can create a custom route for that, **but I wound't recommend it**, it's an heavy process, and if you website has hundreds of page views, it will bloat your server CPU with thumbnail renders.

I recommend you to create the thumbnail when you upload the image.
You can find more on the docs; https://backpackforlaravel.com/docs/4.1/crud-fields#image-1


If you want to generate the thumbnail besides saving your image, after the main image save, you can use something like; 

```php
$size = 128;

$image->resize($size, null, function ($c) {$c->aspectRatio();});
Storage::disk($disk)->put("$path/$size/$filename", $image->stream($format, $quality));
```

For now I'll close this issue since it's not related with FileManager, but feel free to ask anything else if you need ✌
