### ISSUE TITLE
404 after fresh install

### ISSUE THREAD

**Issue by greimers** [Laravel-Backpack/FileManager#24]
I just added FileManager to my project with the steps described in the ReadMe.
But when I navigate to `/admin/elfinder` I simply get a 404 error.

I could not find anything on what I am doing wrong. I haven't modified any configs and Backpack is running fine (also with standard config).

I'm using Laravel 9.19, with backpack CRUD 5.1.3 and FileManager 2.0

**Comment by promatik** [comment]
Hi @greimers!
Sorry for the late reply.
I've just tested to install filemanager and everything worked as expected.

The routes are actually provided by `elfinder-laravel` package, which is a dependency of `backpack-filemanager`. Backpack FileManager modifies the routes with the config file. 

For anyone who may have this error, please make sure the config file is published at `config/elfinder.php` (publishing the views and configs is a step of the installation).

I'll close this one since it's been a long time, if anyone still have any installation issues please let us know.
